### ISSUE TITLE
Learn basics feedback

### ISSUE THREAD

**Issue by leggsimon** [zeit/next-site#28]
Hi, I'm currently going through the learn the basics walkthrough which I must say is one of the best tech onboardings I've ever done. It's really nice.

One thing I'd like clarification on though is this on [`/navigate-between-pages`](https://nextjs.org/learn/basics/navigate-between-pages):
>After that, we need to connect these pages. We could use an HTML "a" tag for that. However, it won't perform client-side navigation; it navigates to the page via the server, which is not what we want.

Why isn't that what we want? It currently doesn't seem clear to be why we want client-side navigation instead and what the benefit is? Are you able to clarify this?

I wonder whether it could/should go into a little bit of detail as to what the benefit is.

**Comment by sergiodxa** [comment]
If you use a normal `<a />` to navigate between pages what's going to happen is the browser will send another request to the server for the whole HTML meaning the server will render again.

If you use `next/link` component to navigate between pages Next.js will only download (if not already prefetched) the JS bundle of the requested page and do the page change client side. This not only let you avoid the server to server render (which takes time and is single thread) but also gives a better UX since you could render a loading indicator if the pages takes too long to load to show the user the page is loading or in the best case scenario will render almost immediately client side as a Single Page Application.

**Comment by xhy82** [comment]
14bit pipeline ADC

**Comment by lfades** [comment]
I'm closing this for now because the section has been improved to better explain the concept.
