### ISSUE TITLE
In the doc and I found the some errors of interaction

### ISSUE THREAD

**Issue by zsirfs** [zeit/next-site#314]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
![2019-04-22 16 36 09](https://user-images.githubusercontent.com/22249411/56492123-579ee980-651d-11e9-86d7-4584d4b9b8b6.gif)

Please see the gif.

**Comment by MarchWorks** [comment]
It's working for me, which browser and its version are you using?

**Comment by timneutkens** [comment]
Specifically hovering the corner of the element causes this weird select/unselected state. I can reproduce on chrome.

**Comment by MarchWorks** [comment]
I was able to reproduce it just one time from at least 10 min of trying to do so. I think that it has something to do with the cursor, I am on windows

**Comment by zsirfs** [comment]
@MarchWorks  In my mac, it's version info:

```
macos: 13.14
chrome: v74

```

**Comment by Tomekmularczyk** [comment]
It happens when you hover on bottom of an element.
It doesn't happen on current Safari or Firefox versions.
It's caused by `overflow: hidden;` property which is there to trigger [Block Formatting Context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context#Margin_collapsing) and prevent margin collapsing.
Weird thing is that if I change `:hover` property from opacity to color it somehow fixes the problem too.

https://monosnap.com/file/mjpCHCH0Br8TtafX0WpfSFjeQR81iK
