### ISSUE TITLE
Update prefetching docs

### ISSUE THREAD

**Issue by Timer** [zeit/next-site#423]
Learn page: https://nextjs.org/learn/basics/navigate-between-pages

Message:
>  <Link /> will prefetch the page and navigation will happen without a page refresh.

We need to clarify that this happens in production only, not development.

**Comment by chibicode** [comment]
From an educational perspective, I think we might **not** want to mention prefetching at all here since it's very early in the tutorial and might just confuse learners who're not familiar with prefetching. The focus here should be to show them that the navigation will happen without a page refresh, and they can learn about prefetching later if needed.

Also, on the same paragraph, I'd avoid using the word "API" here. Currently it says:

> we need to use Next.js's Link API, which is exported via `next/link`.

I think the better word is **component**, because that's what's being exported. Some beginner programmers might have a mental model that says: *"API == something to do with backend server, REST, JSON, etc"*. So I'd reserve the word "API" until we actually talk about API routes.

So I'd suggest rephrasing the paragraph as:

> In order to support client-side navigation, we need to use Next.js's `Link` component, which is exported via `next/link`. By using the `Link` component, navigation will happen without a page refresh.

And I'd also remove the comment `// This is the Link API` [from `using-link` page](https://nextjs.org/learn/basics/navigate-between-pages/using-link). This comment doesn't add any value.

**Comment by lfades** [comment]
@chibicode It all sounds good ❤️

**Comment by chibicode** [comment]
@lfades thanks, will do!
