### ISSUE TITLE
How to debug client-side code?

### ISSUE THREAD

**Issue by Windrushfarer** [zeit/next-site#440]
I wanted to help with issue, but I don't understand why I can't debug any client-side code on same pages?
For example, I put log inside `useEffect` inside function that renders documentation page without any dependecies (this works like `componentDidMount`), but it didn't log anything 🤷‍♂️
Am I doing something wrong?

UPD: Put log inside `componentDidMount` inside tabs component and that worked

**Comment by lfades** [comment]
The docs page (`/pages/docs/index.js`) is using AMP, any code inside `useEffect` will not work, because AMP doesn't allow custom scripts, what Next.js does is prerender the page to valid AMP html, any code inside `useEffect` won't get executed, you can update the styles and use sync javascript (this is my way of saying javascript that only needs to be executed once on build)

**Comment by timneutkens** [comment]
Please follow the issue template.

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```
