### ISSUE TITLE
Passed property becomes undefined

### ISSUE THREAD

**Issue by teleginzhenya** [zeit/next-site#451]
Hi!
#### Problem:
While doing #422 I faced problem that passed property becomes undefined.
In `pages/docs/index.js` I've used intersection observer to get current menu item, then I tried to pass value to `components/docs/sidebar`. At first it has proper value, right after that it becomes undefined.

I have no idea what's wrong ¯\\_(ツ)_/¯ 

#### How to reproduce:
1. clone [my fork](https://github.com/teleginzhenya/next-site/tree/feature/highlight-docs-menu)
`git clone https://github.com/teleginzhenya/next-site.git`
2. checkout to `feature/highlight-docs-menu`
`git checkout feature/highlight-docs-menu`
3. install dependencies
`npm install`
4. run in dev
`npm run dev`
5. go to `/docs` page

#### Example log:
```
currentMenuItem in docs dynamic-routing
currentMenuItem in sidebar dynamic-routing
currentMenuItem in sidebar undefined
currentMenuItem in docs dynamic-routing
currentMenuItem in sidebar dynamic-routing
currentMenuItem in sidebar undefined
```

**Comment by lfades** [comment]
Can you check if it works without using `React.memo`? Also if you want to use React hooks instead please go ahead, it may get you a better understading about what's happening.

@teleginzhenya Because this is an issue with your fork and not with the project itself I'm closing it. Please continue the conversation in the respective issue: https://github.com/zeit/next-site/issues/422
